[package]
name = "gamert"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ash = "0.38.0"
glam = "0.30.3"
gpu-allocator = "0.27.0"
image = "0.25.6"
include_bytes_aligned = "0.1.4"
thiserror = "2.0.12"
winit = "0.30.11"
